# Generated by Django 5.0.7 on 2024-12-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria_5_1_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('scheme_name', models.CharField(max_length=255)),
                ('government_or_non_government', models.CharField(choices=[('Government', 'Government'), ('Non-Government', 'Non-Government')], max_length=15)),
                ('individual_or_organization_name', models.CharField(max_length=255)),
                ('number_of_students_benefited', models.IntegerField()),
                ('amount_in_inr', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
