# Generated by Django 5.0.7 on 2024-12-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_5', '0004_criteria_5_2_1_1_criteria_5_2_1_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria_5_3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name_of_award_medal', models.CharField(max_length=255)),
                ('team_or_individual', models.CharField(choices=[('Team', 'Team'), ('Individual', 'Individual')], max_length=50)),
                ('level_of_competition', models.CharField(choices=[('University', 'University'), ('State', 'State'), ('National', 'National'), ('International', 'International')], max_length=50)),
                ('nature_of_competition', models.CharField(choices=[('Sports', 'Sports'), ('Cultural', 'Cultural')], max_length=50)),
                ('name_of_students', models.TextField(help_text='Enter names separated by commas for team awards')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_5_3_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2021, 'June 2021 - 2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')])),
                ('date_of_event', models.DateField()),
                ('name_of_event', models.CharField(max_length=255)),
                ('name_of_organising_institution', models.CharField(max_length=255)),
                ('name_of_student_participated', models.TextField(help_text='Enter names separated by commas')),
            ],
        ),
    ]
