# Generated by Django 5.0.7 on 2024-12-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_5', '0005_criteria_5_3_1_criteria_5_3_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria_5_2_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('registration_or_roll_number', models.CharField(help_text='Enter the registration or roll number for the exam', max_length=100)),
                ('student_name', models.CharField(help_text='Enter the name of the student qualified', max_length=255)),
                ('qualifying_exam_name', models.CharField(help_text='Enter the name of the qualifying exam', max_length=255)),
            ],
        ),
    ]
