# Generated by Django 5.0.7 on 2024-12-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_5', '0006_criteria_5_2_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria_5_1_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'All of the above'), ('B', 'Any 3 of the above'), ('C', 'Any 2 of the above'), ('D', 'Any 1 of the above'), ('E', 'None of the above')], default='E', max_length=1)),
            ],
        ),
    ]
