# Generated by Django 5.0.7 on 2024-12-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usercriterialink_delete_criterialink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercriterialink',
            name='criteria',
            field=models.CharField(choices=[('2_7_1', 'Criteria 2.7.1'), ('2_6_3', 'Criteria 2.6.3'), ('3_1_1', 'Criteria 3.1.1'), ('3_2_2', 'Criteria 3.2.2'), ('3_3_1', 'Criteria 3.3.1'), ('3_5_1', 'Criteria 3.5.1'), ('4_1_2', 'Criteria 4.1.2')], max_length=10),
        ),
    ]
