# Generated by Django 5.0.7 on 2024-07-19 06:41

import criteria_1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria_1_1_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('description', models.TextField(validators=[criteria_1.models.validate_word_count])),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_1_2_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_1_2_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2021, 'June 2021 - 2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')])),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('year_of_study', models.IntegerField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('students_enrolled', models.IntegerField()),
                ('students_completed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_1_3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('description', models.TextField(validators=[criteria_1.models.validate_word_count])),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_1_3_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('programme_name', models.CharField(max_length=255)),
                ('programme_code', models.CharField(max_length=50)),
                ('student_list', models.TextField()),
                ('document_link', models.URLField()),
            ],
        ),
    ]
