# Generated by Django 5.0.7 on 2024-12-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria_1_1_1',
            name='year',
        ),
        migrations.RemoveField(
            model_name='criteria_1_3_1',
            name='year',
        ),
        migrations.AddField(
            model_name='criteria_1_1_1',
            name='additional_information_file',
            field=models.FileField(blank=True, help_text='Upload any additional information if available.', null=True, upload_to='criteria_1/1_1_1/'),
        ),
        migrations.AddField(
            model_name='criteria_1_1_1',
            name='additional_information_link',
            field=models.URLField(blank=True, help_text='Provide the link for additional information.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='criteria_1_3_1',
            name='additional_information_file',
            field=models.FileField(blank=True, help_text='Upload any additional information if available.', null=True, upload_to='criteria_1/1_3_1/'),
        ),
        migrations.AddField(
            model_name='criteria_1_3_1',
            name='additional_information_link',
            field=models.URLField(blank=True, help_text='Provide the link for additional information.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='criteria_1_1_1',
            name='description',
            field=models.TextField(help_text='Write the description in a maximum of 500 words.'),
        ),
        migrations.AlterField(
            model_name='criteria_1_3_1',
            name='description',
            field=models.TextField(help_text='Write the description in a maximum of 500 words.'),
        ),
    ]
