# Generated by Django 5.0.7 on 2024-10-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_1', '0003_criteria_1_2_2_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria_1_2_2',
            name='assigned_to',
        ),
    ]
