# Generated by Django 5.0.7 on 2024-12-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_6', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria_6_3_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name_of_participant', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('title_of_program', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
    ]
