# Generated by Django 5.0.7 on 2024-12-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_6', '0002_criteria_6_3_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria_6_1_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Describe in a maximum of 500 words.')),
                ('additional_information_file', models.FileField(blank=True, help_text='Upload additional information if available.', null=True, upload_to='criteria_6/6_1_1/')),
                ('additional_information_link', models.URLField(blank=True, help_text='Provide a link for additional information if available.', max_length=500, null=True)),
            ],
        ),
    ]
