# Generated by Django 5.0.7 on 2024-12-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_7', '0004_criteria_7_2_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria_7_1_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'Any 4 or more of the above'), ('B', 'Any 3 of the above'), ('C', 'Any 2 of the above'), ('D', 'Any 1 of the above'), ('E', 'None of the above')], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_7_1_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'All of the above'), ('B', 'Any 3 of the above'), ('C', 'Any 2 of the above'), ('D', 'Any 1 of the above'), ('E', 'None of the above')], default='E', max_length=1)),
            ],
        ),
    ]
