# Generated by Django 5.0.7 on 2024-07-11 15:28

import criteria_3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria_3_1_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')])),
                ('project_name', models.CharField(max_length=255)),
                ('principal_investigator', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('year_of_award', models.IntegerField()),
                ('amount_sanctioned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('funding_agency', models.CharField(max_length=255)),
                ('grant_type', models.CharField(choices=[('Government', 'Government'), ('Non-Government', 'Non-Government')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_3_2_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')])),
                ('description', models.TextField(validators=[criteria_3.models.validate_word_count])),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_3_2_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')])),
                ('event_name', models.CharField(max_length=255)),
                ('num_participants', models.PositiveIntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('activity_report_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_3_3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')])),
                ('title_of_paper', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=255)),
                ('journal_name', models.CharField(max_length=255)),
                ('issn_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ugc_recognition_link', models.URLField(blank=True, null=True)),
                ('journal_website_link', models.URLField(blank=True, null=True)),
                ('article_link', models.URLField(blank=True, null=True)),
                ('is_ugc_care_listed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_3_3_2',
            fields=[
                ('year', models.PositiveIntegerField(choices=[(2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')])),
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=255)),
                ('book_or_chapter_title', models.CharField(blank=True, max_length=255, null=True)),
                ('paper_title', models.CharField(blank=True, max_length=255, null=True)),
                ('proceedings_title', models.CharField(blank=True, max_length=255, null=True)),
                ('conference_name', models.CharField(blank=True, max_length=255, null=True)),
                ('conference_type', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=20)),
                ('publication_year', models.PositiveIntegerField()),
                ('isbn_number', models.CharField(blank=True, max_length=20, null=True)),
                ('affiliating_institute', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_3_4_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')])),
                ('description', models.TextField(validators=[criteria_3.models.validate_word_count])),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_3_4_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')])),
                ('description', models.TextField(validators=[criteria_3.models.validate_word_count])),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_3_4_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('organizing_unit', models.CharField(max_length=255)),
                ('collaborating_agency', models.CharField(blank=True, max_length=255, null=True)),
                ('scheme_name', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_year', models.PositiveIntegerField(choices=[(2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')])),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_3_5_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')])),
                ('mou_name', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('signing_year', models.PositiveIntegerField()),
                ('pourpose', models.CharField(choices=[('Internship', 'Internship'), ('On-the-job Training', 'On-the-job Training'), ('Project Work', 'Project Work'), ('Student/Faculty Exchange', 'Student/Faculty Exchange'), ('Collaborative Research', 'Collaborative Research')], max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('activities', models.TextField()),
                ('document_link', models.URLField()),
            ],
        ),
    ]
