# Generated by Django 5.0.7 on 2024-12-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Criteria_3_4_3',
        ),
    ]
