# Generated by Django 5.0.7 on 2024-07-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria_3_4_3',
            name='collaborating_agency',
        ),
        migrations.AddField(
            model_name='criteria_3_4_3',
            name='year',
            field=models.IntegerField(choices=[(2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')], default=1),
            preserve_default=False,
        ),
    ]
