# Generated by Django 5.0.7 on 2024-07-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_3', '0002_remove_criteria_3_4_3_collaborating_agency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria_3_3_1',
            name='ugc_recognition_link',
        ),
        migrations.AddField(
            model_name='criteria_3_3_1',
            name='year_of_publication',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
