# Generated by Django 5.0.7 on 2024-12-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_3', '0002_delete_criteria_3_4_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria_3_4_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_activity', models.CharField(max_length=255)),
                ('organising_unit_or_agency_or_collaborating_agency', models.CharField(max_length=255)),
                ('name_of_scheme', models.CharField(max_length=255)),
                ('year_of_activity', models.IntegerField()),
            ],
        ),
    ]
