# Generated by Django 5.0.7 on 2024-12-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_3', '0003_criteria_3_4_3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Criteria_3_3_2',
        ),
    ]
