# Generated by Django 5.0.7 on 2024-12-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_3', '0006_delete_criteria_3_3_2_delete_criteria_3_4_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria_3_3_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_teacher', models.CharField(max_length=255)),
                ('title_of_book_or_chapters_published', models.CharField(blank=True, max_length=500, null=True)),
                ('title_of_paper', models.CharField(blank=True, max_length=500, null=True)),
                ('title_of_proceedings_of_conference', models.CharField(blank=True, max_length=500, null=True)),
                ('name_of_conference', models.CharField(blank=True, max_length=255, null=True)),
                ('national_or_international', models.CharField(blank=True, choices=[('National', 'National'), ('International', 'International')], max_length=50, null=True)),
                ('calendar_year_of_publication', models.IntegerField()),
                ('isbn_number_of_proceeding', models.CharField(blank=True, max_length=20, null=True)),
                ('affiliating_institute_at_time_of_publication', models.CharField(max_length=255)),
                ('name_of_publisher', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_3_4_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_activity', models.CharField(max_length=255)),
                ('organising_unit_or_agency_or_collaborating_agency', models.CharField(max_length=255)),
                ('name_of_scheme', models.CharField(max_length=255)),
                ('year_of_activity', models.IntegerField()),
            ],
        ),
    ]
