# Generated by Django 5.0.7 on 2024-12-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_2', '0002_remove_criteria_2_3_1_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria_2_3_1',
            name='additional_information_file',
            field=models.FileField(blank=True, help_text='Upload any additional information if available.', null=True, upload_to='criteria_2/2_3_1/'),
        ),
        migrations.AlterField(
            model_name='criteria_2_5_1',
            name='additional_information_file',
            field=models.FileField(blank=True, help_text='Upload any additional information if available.', null=True, upload_to='criteria_2/2_5_1/'),
        ),
        migrations.AlterField(
            model_name='criteria_2_6_1',
            name='additional_information_file',
            field=models.FileField(blank=True, help_text='Upload any additional information if available.', null=True, upload_to='criteria_2/2_6_1/'),
        ),
        migrations.AlterField(
            model_name='criteria_2_6_2',
            name='additional_information_file',
            field=models.FileField(blank=True, help_text='Upload any additional information if available.', null=True, upload_to='criteria_2/2_6_2/'),
        ),
    ]
