# Generated by Django 5.0.7 on 2024-12-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_2', '0004_criteria_2_4_2_1_criteria_2_4_2_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria_2_4_2_1',
            name='year_of_obtaining_qualification',
        ),
        migrations.RemoveField(
            model_name='criteria_2_4_2_2',
            name='year_of_obtaining_qualification',
        ),
    ]
