# Generated by Django 5.1.3 on 2024-11-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria_4_1_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')])),
                ('description', models.TextField(help_text='Describe the adequacy of facilities in a maximum of 500 words.')),
                ('additional_information_file', models.FileField(blank=True, help_text='Upload additional information if available.', null=True, upload_to='criteria_4_1_1/')),
                ('additional_information_link', models.URLField(blank=True, help_text='Provide a link for additional information if available.', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_4_1_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')])),
                ('head_of_expenditure', models.CharField(help_text='e.g., Capital Expenditure', max_length=255)),
                ('item_of_expenditure', models.CharField(help_text='e.g., Construction of building, purchase of equipment, etc.', max_length=255)),
                ('amount_in_lakhs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_4_1_2_Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')])),
                ('total_amount_in_lakhs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_4_2_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('description', models.TextField(help_text="Describe the library's digital facilities, automation, and usage in a maximum of 500 words.")),
                ('additional_information_file', models.FileField(blank=True, help_text='Upload additional information if available.', null=True, upload_to='criteria_4_2_1/')),
                ('additional_information_link', models.URLField(blank=True, help_text='Provide a link for additional information if available.', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_4_3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('description', models.TextField(help_text='Describe IT facilities, including Wi-Fi, updates (with dates and nature of updates), and internet bandwidth within a maximum of 500 words.')),
                ('additional_information_file', models.FileField(blank=True, help_text='Upload additional information if available.', null=True, upload_to='criteria_4_3_1/')),
                ('additional_information_link', models.URLField(blank=True, help_text='Provide a link for additional information if available.', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_4_3_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Latest completed academic year')),
                ('number_of_students', models.IntegerField(help_text='Total number of students during the latest completed academic year')),
                ('number_of_computers', models.IntegerField(help_text='Number of computers available for student usage during the latest completed academic year')),
                ('supporting_document', models.FileField(blank=True, help_text='Upload supporting documents if available.', null=True, upload_to='criteria_4_3_2/')),
                ('additional_information_link', models.URLField(blank=True, help_text='Provide links for any other relevant documents to support the claim.', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_4_4_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')])),
                ('head_of_expenditure', models.CharField(help_text='e.g., Repair and Maintenance', max_length=255)),
                ('item_of_expenditure', models.CharField(help_text='e.g., AMC for Lab equipment, garden maintenance, etc.', max_length=255)),
                ('amount_in_lakhs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_4_4_1_Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')])),
                ('total_amount_in_lakhs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
