# Generated by Django 5.1.3 on 2024-11-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria_4_2_1',
            name='year',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')]),
        ),
        migrations.AlterField(
            model_name='criteria_4_3_1',
            name='year',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')]),
        ),
        migrations.AlterField(
            model_name='criteria_4_3_2',
            name='year',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')]),
        ),
    ]
