# Generated by Django 5.0.7 on 2024-11-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_4', '0002_alter_criteria_4_2_1_year_alter_criteria_4_3_1_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria_4_1_1',
            name='year',
        ),
        migrations.AlterField(
            model_name='criteria_4_1_2',
            name='year',
            field=models.IntegerField(choices=[(2021, 'June 2021 - 2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')]),
        ),
        migrations.AlterField(
            model_name='criteria_4_1_2_total',
            name='year',
            field=models.IntegerField(choices=[(2021, 'June 2021 - 2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026')]),
        ),
    ]
