# Generated by Django 5.0.7 on 2024-12-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_4', '0003_remove_criteria_4_1_1_year_alter_criteria_4_1_2_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Criteria_4_1_2_Total',
        ),
        migrations.RemoveField(
            model_name='criteria_4_2_1',
            name='year',
        ),
        migrations.RemoveField(
            model_name='criteria_4_3_1',
            name='year',
        ),
        migrations.RemoveField(
            model_name='criteria_4_3_2',
            name='year',
        ),
    ]
