# Generated by Django 5.0.7 on 2024-12-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_4', '0004_delete_criteria_4_1_2_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria_4_1_1',
            name='additional_information_file',
            field=models.FileField(blank=True, help_text='Upload additional information if available.', null=True, upload_to='criteria_4/4_1_1/'),
        ),
        migrations.AlterField(
            model_name='criteria_4_2_1',
            name='additional_information_file',
            field=models.FileField(blank=True, help_text='Upload additional information if available.', null=True, upload_to='criteria_4/4_2_1/'),
        ),
        migrations.AlterField(
            model_name='criteria_4_3_1',
            name='additional_information_file',
            field=models.FileField(blank=True, help_text='Upload additional information if available.', null=True, upload_to='criteria_4/4_3_1/'),
        ),
    ]
