# Generated by Django 5.0.7 on 2024-12-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_4', '0006_alter_criteria_4_4_1_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Criteria_4_4_1_Total',
        ),
    ]
